# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/Desktop/EE-26---Digital-Logic-Systems/lock/lock.cache/wt [current_project]
set_property parent.project_path Z:/Desktop/EE-26---Digital-Logic-Systems/lock/lock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  Z:/Desktop/EE-26---Digital-Logic-Systems/lock/lock.srcs/sources_1/new/combination_lock.vhd
  Z:/Desktop/EE-26---Digital-Logic-Systems/lock/lock.srcs/sources_1/new/seven_seg_display.vhd
  Z:/Desktop/EE-26---Digital-Logic-Systems/lock/lock.srcs/sources_1/new/lock.vhd
}
read_xdc Z:/Desktop/EE-26---Digital-Logic-Systems/lock/lock.srcs/constrs_1/new/lock_constraints.xdc
set_property used_in_implementation false [get_files Z:/Desktop/EE-26---Digital-Logic-Systems/lock/lock.srcs/constrs_1/new/lock_constraints.xdc]

catch { write_hwdef -file lock.hwdef }
synth_design -top lock -part xc7a100tcsg324-1
write_checkpoint -noxdef lock.dcp
catch { report_utilization -file lock_utilization_synth.rpt -pb lock_utilization_synth.pb }
