# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/Documents/EE26/tutorial/tutorial.cache/wt [current_project]
set_property parent.project_path Z:/Documents/EE26/tutorial/tutorial.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib C:/Users/ajayak02/Downloads/vhdl_tutorial_xilinx/vhdl_tutorial_xilinx/vhdl_tutorial_xilinx.srcs/sources_1/imports/Tutorial/tutorial.vhd
read_xdc C:/Users/ajayak02/Downloads/vhdl_tutorial_xilinx/vhdl_tutorial_xilinx/vhdl_tutorial_xilinx.srcs/constrs_1/imports/Tutorial/tutorial.xdc
set_property used_in_implementation false [get_files C:/Users/ajayak02/Downloads/vhdl_tutorial_xilinx/vhdl_tutorial_xilinx/vhdl_tutorial_xilinx.srcs/constrs_1/imports/Tutorial/tutorial.xdc]

read_xdc Z:/Documents/EE26/tutorial/tutorial.srcs/constrs_1/new/tutorial.xdc
set_property used_in_implementation false [get_files Z:/Documents/EE26/tutorial/tutorial.srcs/constrs_1/new/tutorial.xdc]

catch { write_hwdef -file tutorial.hwdef }
synth_design -top tutorial -part xc7a100tcsg324-1
write_checkpoint -noxdef tutorial.dcp
catch { report_utilization -file tutorial_utilization_synth.rpt -pb tutorial_utilization_synth.pb }
