# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/Documents/EE26/project1/4_bit_ripple_carry_adder/4_bit_ripple_carry_adder.cache/wt [current_project]
set_property parent.project_path Z:/Documents/EE26/project1/4_bit_ripple_carry_adder/4_bit_ripple_carry_adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  Z:/Documents/EE26/project1/4_bit_ripple_carry_adder/4_bit_ripple_carry_adder.srcs/sources_1/new/4_bit_ripple_carry_adder.vhd
  Z:/Documents/EE26/project1/4_bit_ripple_carry_adder/4_bit_ripple_carry_adder.srcs/sources_1/new/4_bit_subtractor.vhd
  Z:/Documents/EE26/project1/4_bit_ripple_carry_adder/4_bit_ripple_carry_adder.srcs/sources_1/new/4_bit_subtractor_tb.vhd
  Z:/Documents/EE26/project1/4_bit_ripple_carry_adder/4_bit_ripple_carry_adder.srcs/sources_1/new/mux.vhd
}
catch { write_hwdef -file four_bit_ripple_carry_adder.hwdef }
synth_design -top four_bit_ripple_carry_adder -part xc7a100tcsg324-1
write_checkpoint -noxdef four_bit_ripple_carry_adder.dcp
catch { report_utilization -file four_bit_ripple_carry_adder_utilization_synth.rpt -pb four_bit_ripple_carry_adder_utilization_synth.pb }
