# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ajayak02.HLGN/Downloads/EE-26---Digital-Logic-Systems-master/EE-26---Digital-Logic-Systems-master/sixteen_bit_claa/sixteen_bit_claa.cache/wt [current_project]
set_property parent.project_path C:/Users/ajayak02.HLGN/Downloads/EE-26---Digital-Logic-Systems-master/EE-26---Digital-Logic-Systems-master/sixteen_bit_claa/sixteen_bit_claa.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/ajayak02.HLGN/Downloads/EE-26---Digital-Logic-Systems-master/EE-26---Digital-Logic-Systems-master/sixteen_bit_claa/sixteen_bit_claa.srcs/sources_1/imports/new/full_adder.vhd
  C:/Users/ajayak02.HLGN/Downloads/EE-26---Digital-Logic-Systems-master/EE-26---Digital-Logic-Systems-master/sixteen_bit_claa/sixteen_bit_claa.srcs/sources_1/imports/new/for_bit_cla_pg.vhd
  C:/Users/ajayak02.HLGN/Downloads/EE-26---Digital-Logic-Systems-master/EE-26---Digital-Logic-Systems-master/sixteen_bit_claa/sixteen_bit_claa.srcs/sources_1/imports/new/four_bit_claa_pg.vhd
  C:/Users/ajayak02.HLGN/Downloads/EE-26---Digital-Logic-Systems-master/EE-26---Digital-Logic-Systems-master/sixteen_bit_claa/sixteen_bit_claa.srcs/sources_1/imports/new/sixteen_bit_claa.vhd
}
catch { write_hwdef -file sixteen_bit_claa.hwdef }
synth_design -top sixteen_bit_claa -part xc7a100tcsg324-1
write_checkpoint -noxdef sixteen_bit_claa.dcp
catch { report_utilization -file sixteen_bit_claa_utilization_synth.rpt -pb sixteen_bit_claa_utilization_synth.pb }
